Makefile, Vagrantfile, isso/demo/index.html, share/isso-dev.conf, share/isso-dev.local.apache-conf
I've created a Vagrantfile to make it easy to get a test environment up and running with the demo page - Vagrant will spin up a VM with node.js, uWSGI, Apache2, and register everything such that you can immediately view the demo page at http://isso-dev.local/ and start trying out code changes.
Doesn't affect the end user but should make it nicer for me to work with :) maybe helpful for other people too?
=> Vagrant support

Vagrantfile
uglifyjs has been [unpublished](https://www.npmjs.com/package/uglifyjs). Instead use uglify-js.
=> Fix npm uglifyjs missing package error

isso/db/preferences.py
The session-key should be saved as a string, not a byte string.
=> Save the session-key as a unicode string in the db

isso/ext/notifications.py
If no username is set, returns an empty string. So the test `username is
not None` is always True. Idem for password. This can lead to
authentication problems. This commit fixes the test to `if username and
password` as it was in the previous version.
Full error message:
```
2015-03-07 16:04:03,456 ERROR: unable to connect to SMTP server
Traceback (most recent call last):
File "/home/blog/comments/lib/python2.7/site-packages/isso/ext/notifications.py", line 42, in __init__
with self:
File "/home/blog/comments/lib/python2.7/site-packages/isso/ext/notifications.py", line 75, in __enter__
self.client.login(username, password)
File "/usr/lib64/python2.7/smtplib.py", line 578, in login
raise SMTPException("SMTP AUTH extension not supported by server.")
SMTPException: SMTP AUTH extension not …
```
=> Correct auth without password or username.

CONTRIBUTORS.txt, docs/docs/configuration/client.rst, docs/docs/configuration/server.rst, isso/db/spam.py, isso/js/app/config.js, isso/js/app/isso.js, isso/tests/test_guard.py, share/isso.conf
This patch adds a parameter to make requiring an email address configurable.
Could probably be improved by:
* ~~write tests~~
* using HTML5 form validation
* not using a nasty regex substitute to remove `(required)` from the placeholder (or internationalised equivalent)
=> Add configuration to make email a required field

setup.py
With the release of misaka 2.0, new users experienced breakage when
2.0 was installed (#208).
2.0 has a slightly different API, and Python 2.6 support in 2.0 is not
yet released. #212 contains the update to 2.0, so this change should
only be a stopgap until the next misaka release with Py2.6 support.
=> Pin misaka to 1.x

CONTRIBUTORS.txt, ansible/site.yml
`vagrant up` dies without `libffi-dev` installed
=> Make Vagrant actually work

Makefile
WIthout this, building the manpages fails for me as git doesn't version empty directories.
=> Create man page directory before moving files to them.

Makefile
This is useful for platforms like Debian that don't ship with r.js in
the path.
=> Add make variable for r.js, so it can easily be overriden.

docs/docs/configuration/client.rst, isso/js/app/isso.js, isso/views/comments.py
Hello,
Here is a fix for the use of data-isso-id.
The problem was that thread ids needs to be URL because of an http curl used to check title of the page. 
I changed this behaviour a little by saying that if you provide a title (using the data-title documented in the client configuration), we don't need to send a curl request to get the title and just grab it. Incidently it makes custom thread id work since the curl to get the title is the only reason thread id is an URL (at least I didn't was any other need for this constraint).
Tell me if any changes needs to be made to the PR.
=> Fix issue #27 on override thread discovery with custom data-attributes

docs/docs/configuration/client.rst, isso/css/isso.css, isso/js/app/config.js, isso/js/app/dom.js, isso/js/app/isso.js, isso/js/app/text/comment.jade
https://github.com/posativ/isso/commit/b0f8606b0f1484f4bea6f0e0f9235247cb0d0766 removes hard-coded behavior that vote count must be hidden when the value is 0. This is now done through CSS.
Use case:
- Ability to disable the default behavior of hiding 0 votes (using CSS overrides)
The other two commits introduce the ability to attach custom classes on comments based on the number of votes. See the changes in documentation for more details.
Use cases:
- Red number when votes < 0, green when >0
- Collapse or gray out comments with many negative votes
- Award good comments with visual flair (eg. a different background color)
=> Vote levels

isso/js/app/i18n/zh_CN.js, isso/js/app/i18n/zh_TW.js
This fixes #262
Probably there are better ways to handle "(optional)" by not using regexes.
=> fix "optional" in zh translations

docs/docs/extras/advanced-integration.rst
It looks like multiple comment counters now result in a single `GET` request (a very good thing!) as of 5ce48de.  This updates the docs to reflect that.
=> update doc to reflect 5ce48de

isso/css/isso.css
=> Highlight links by underline in comments

docs/_isso/layout.html
With Sphinx 1.5, this is needed by searchtools.js to display the source
snippets (see sphinx-doc/sphinx#2454).
With earlier Sphinx versions, this is a no-op because the undefined variable
will evaluate to an empty string.
=> add SOURCELINK_SUFFIX for compatibility with Sphinx 1.5

isso/js/app/i18n.js
Fixes an indexing error a user gets when he tries to make the language of isso to `bg`
=> fix: add missing i18n entry

isso/js/app/i18n.js
Allow the user configure language to "zh", "zh_CN", "zh_TW", and make them work as expected.
=> Better configure options for Chinese language

isso/js/app/lib/identicons.js
Hex-digits with character count above 17 cannot be safely converted to an Integer, see [MAX_SAFE_INTEGER](https://medium.com/the-node-js-collection/javascripts-number-type-8d59199db1b6#53cd).
Therefore, when long keys (e.g. 32 characters) are passed into `generateIdenticon()`, and the modulus of 2^18 is performed, the result is 0 all the time. This means, the identicon will render as an empty svg image.
Here is a proof-of-concept (run in any modern browser):
```js
const key = '841b625dcf75413ff3ed5137a81ff1c3';
const int = parseInt(key, 16);
const hash = int % Math.pow(2, 18);
// throws, due to floating point conversion / integer overflow
console.assert(258499 === hash, "Modulus for 'hash' should be != 0");
const int2 = parseInt(key.substr(-16), 16);
const hash2 = int2 % Math.pow(2, 18); …
```
=> Fix: Truncate key-length when generating identicons

isso/js/app/i18n.js
#350 introduces an error per https://github.com/posativ/isso/pull/350#issuecomment-345892951
=> Fix hungarian translation

isso/css/isso.css
Previously color contrast was insufficient per WCAG AA
=> Darken placeholder text

.travis.yml, docs/docs/install.rst, isso/compat.py, isso/config.py, isso/tests/test_comments.py, isso/tests/test_config.py, isso/tests/test_cors.py, isso/tests/test_db.py, isso/tests/test_guard.py, isso/tests/test_html.py, isso/tests/test_migration.py, isso/tests/test_utils.py, isso/tests/test_utils_hash.py, isso/tests/test_vote.py, isso/tests/test_wsgi.py, setup.py, tox.ini
Fixes #379
Also steps up from pyflakes to [flake8](http://flake8.pycqa.org) for testing.
=> Drop support for python 2.6 and 3.3

Dockerfile, docs/docs/install.rst
Many of the Docker images on hub.docker.com are outdated. The one
specified in the documentation doesn't exist anymore. We provide a
decent Dockerfile to build our own Docker image.
This uses a multi-stage build to avoid polluting the final image with
the intermediate artifacts. The final image is 155 MB. It should be
possible to squeeze it even more by using Alpine Linux for the last
two parts instead of Stretch.
The service is using gunicorn. The user is expected to complete the
installation with a reverse proxy configuration.
=> Provide a multi-staged Dockerfile

isso/views/comments.py
If someone visit demo page with querystrng, like `http://isso.example.com/demo?a` , there would be an error caused by too many redirects. So before the url string was joint, querystring should be striped.
After login the admin page, the actual redirect url would be `http://isso.example.com//admin` . There is an extra `/` and the browser would just goto `http://isso.example.com/` other than `http://isso.example.com/admin` , which causes a 'Bad Request'.
this commit fix both 2 bugs above.
=> fix: admin and demo view redirect issue

docs/docs/configuration/client.rst, docs/docs/configuration/server.rst, docs/docs/extras/api.rst, isso/css/isso.css, isso/db/comments.py, isso/js/app/api.js, isso/js/app/config.js, isso/js/app/i18n/en.js, isso/js/app/i18n/fr.js, isso/js/embed.js, isso/tests/test_comments.py, isso/utils/__init__.py, isso/views/comments.py, share/isso.conf
We need absolute URL at some places. We assume the first host
configured is the base of the URI we have.
Fix #81.
This is mostly a "RFC". Notably, tests are missing.
=> api: add /feed API to get an Atom feed for an URI

isso/tests/test_html.py, isso/utils/html.py
"nofollow" is a deterrent for spammers: they cannot put links and hope
to increase their SEO when all these links have the nofollow
relationship.
"noopener" is a security for links opening a new window. They ensure
the target cannot control us.
Fix #373
=> html: add nofollow/noopener to links

isso/js/app/jade.js, isso/js/lib/requirejs-jade/jade.js
Use of eval is handy when we need to automatically reload a
template. However, in production, this is slow and unsafe. Moreover,
when using CSP, we have to use 'unsafe-eval' which brings shame to
most of us. It appears use of eval() is not needed because the
template has already been translated to Javascript. We just need to
bind "jade" to its local scope.
So, we add an additional wrapper function binding "jade" to the local
scope. Moreover, when compiling the template, we add a flag to the
function to know it has already been compiled. In this case, we
execute it with "jade" in its scope. Otherwise, we keep using eval.
Quickly tested in both situations. Seem to work.
Fix #274.
=> jade: avoid using eval once compiled

isso/js/embed.js
When a browser doesn't support DOM manipulation convenience methods,
the addition of the feed link was triggering an error because elements
created by `$.new()` are regular elements, not elements from our own
mini-DOM implementation. Therefore, the `append()` method may be
absent. Use `appendChild()` instead.
=> embed: fix feed link creation on older browsers

Dockerfile
`python setup.py install` installs it outside the virtualenv (because
it's in `setup_requires`?), then reuse it as is when installing the
dependencies. On the final container, cffi is therefore missing.
=> docker: install cffi inside virtualenv

Makefile
The `scss` command has been deprecated, now the `node-sass` command must be used directly.
=> Substituting scss command in Makefile by node-sass + adding comment with instructions on how to install Makefile dependencies

isso/css/isso.scss, isso/db/comments.py, isso/ext/notifications.py, isso/js/app/i18n/en.js, isso/js/app/i18n/fr.js, isso/js/app/isso.js, isso/js/app/text/postbox.html, isso/views/comments.py
Hi,
I love Isso, but the only thing that prevent me to drop Disqus for Isso is the ability for commenters to receive an email notification of reply.
I get a working version with this feature (I use it in production on my blog: http://thomassileo.com), it still need some improvement, I just open the pull request to open the discussion.
What do you think about this feature ?
I added a field in the comment table, is this something that will prevent you to merge this feature ?
Let me know what you think about this,
Thanks!
=> Reply notification

isso/templates/admin.html, isso/templates/login.html, isso/views/comments.py
When the isso root location was 
https://example.com/isso
the administration pages did not work correctly.  The changes in this pull request fix that and allow proper working with or without a subdirectory.  E.g. both of these become valid configurations:
https://example.com
https://example.com/isso
The subdirectory case only requires the subdirectory to be passed as a parameter in the proxy call.  Here is an example *nginx* setup:
location /isso {
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Script-Name /isso;      // <---- critical for subdirectory config
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_pass http://localhost:1234;
}
If the line `proxy_set_header X-Script-Name /isso;` is omitted, communication with *isso* …
=> Allow subdirectory server configuration, e.g. https://example.com/isso

CONTRIBUTORS.txt, docs/docs/extras/advanced-integration.rst, isso/js/app/api.js, isso/js/embed.js
This PR integrates a new feature: async comment loading, especially useful on dynamic websites (eg. websites use PJAX).
`embed.min.js` will define a global object `Isso` under `window`.
Call `Isso.fetchComments()` to re-fetch comments after `section#isso-thread`'s `data-isso-id` attribute was changed (or browser URL changed via `location.pushState`).
And if the thread element was removed, create `section#isso-thread` and call `Isso.init()`, the PostBox and comments would be loaded just as if when page was loaded.
---
PS: 'cause I'm not a native English speaker, the doc may need improvement.
=> Async comment loading for dynamic websites

isso/templates/admin.html
make use of style in isso.css, the admin page layout would be more neat
after:
before:
=> template: admin: add id `isso-root` to comments wrapper

isso/js/app/i18n/ru.js
By the way, what happens if there is no translation for some entry? Isso uses English? For example, there is no Russian translation for "atom-feed", but I think it is OK to display "Atom feed" for Russian users.
=> add  "postbox-notification"

isso/templates/login.html
No need to click on the input form to type in the password, it is active by default
=> Make password form focused on page load

isso/views/comments.py
This way, one can use "/" as base URL. This is only valid if we are
sure that URI should always have a leading "/". Is that the case?
Fix #437.
=> feed: remove trailing / from base URL

isso/js/app/i18n/zh_CN.js, isso/js/app/i18n/zh_TW.js
I haven't relaized that Isso hardcode a space and a pair of ASCII barckets for that `(optional)` substring detection (see below) before I submit PR #469 , which makes postbox name and email always display as optional.
https://github.com/posativ/isso/blob/9c57ac22e5390773089f58c048e9c6ad7e6535b8/isso/js/app/isso.js#L54-L64
Apologize for that mistake, sorry ...
This PR also changes EOL sequence of `zh_TW.js` from CRLF to LF, as all other files do.
=> i18n: fix zh_CN/TW 'optional' in postbox placeholder

isso/wsgi.py
Just something that I never got around to pushing back here.
=> Use AF_INET if AF_UNIX isn't available (i.e. Windows)

isso/js/embed.js
When loading, Isso scrolls to the current document hash. This makes
sense when the document hash references a comment, but this doesn't
for an unrelated anchor. Tell Isso to only scroll for a comment.
=> embed: do not jump to unrelated anchor on load

isso/css/isso.css
This is usually a pain to vertically align without additional markup.
The proposed solution happens to be the shortest solution I know of,
but it may be outdated.
The second commit is to reduce the size of the label. I have put it in another commit as it may not be approved. Feel free to drop it.
=> css: fix vertical alignment of notification checkbox

docs/docs/configuration/client.rst
There is a header describing `data-isso-reply-notifications` but it is not in the initial data attributes examples. I assume the initial list is meant to be exhaustive? I overlooked this setting on my initial read through the docs because it wasn't there, so I thought it would be helpful to add.
=> Add data-isso-reply-notifications to attributes

isso/ext/notifications.py
If the user specifies a public endpoint as `http[s]://comments.exemple.com/` in configuration, the trailing slash will involve a `//` in the generated email links.
This patch should deal about that.
(See #420 OP note.)
---
```
[...]
---
Delete comment: https://comments.exemple.com//id/X/delete/token
```
---
Feedback welcome !
Bye :wave:
=> Removes potential '//' from email links (#420)

docs/docs/extras/advanced-migration.rst, docs/docs/quickstart.rst, isso/__init__.py, isso/migrate.py
Greetings,
The script migrate.py is containing a tool for importing a generic format of comments.
But until now this tool was unreachable from isso binary.
These commits enable the usage of "generic" type of importation. Also I have added some documentation about how using it. The documentation part looks big, I am open to any simplifications.
Regards,
Matthieu
=> Enable the generic migrate function

CONTRIBUTORS.txt, isso/views/comments.py
This closes #358. After a comment is successfully moderated, the user is redirected to the comment page itself.
=> Implement #358 (Redirect to comment after moderation)

isso/tests/test_comments.py, isso/views/comments.py
For some of us who are picky about 404s, the API returns 404 when there are no comments. The not found exception was removed and the endpoint returns empty as expected with HTTP status 200.
`{"id": null, "total_replies": 0, "hidden_replies": 0, "replies": []}`
=> Return 200 with empty array when there are no comments #301

docs/docs/install.rst
- isso is now packaged in official debian
- packages.crapouillou.net is no longer maintained
what else ? :)
=> Mention official Debian repo instead of 3rd party

isso/views/comments.py
The disabled.html template uses the isso_host_script variable, but
that variable was not being passed when rendering that template
file.
=> Fix rendering of disabled.html for 'Sub URI' sites

docs/docs/index.rst
Replaced 'get' with 'run into' as it is more grammatically correct.
=> Improved Grammar of index.rst

isso/views/comments.py
We're using gravatars. Most of our users do not provide e-mails. With the current implementation, different people look the same (they all use default icon) and as such, the avatars aren't very useful.
The proposed change makes gravatars fall back to authors' nicknames when they didn't provide an e-mail. That way, if someone leaves multiple comments under the same nickname, they'll have the same gravatar, but they'll still be different from other users who use different nicknames.
=> use author names in gravatars

isso/css/isso.css
Until this fix, likes counters of replies are only displayed if the parent comment has likes.
This is because the previous CSS rule there applied to **all** HTML children of the element with the `isso-no-votes` class, not only its own footer likes ounter.
With this PR we get the expected behaviour
=> Fixing likes counter of replies not being displayed

isso/views/comments.py
This shows recent comments first in the admin panel.
Personal preference of mine, but maybe others agree?
=> admin: Set default order_by to 'created' (desc)

isso/js/app/i18n/zh_TW.js
The original one was simplified chinese which is for zh_CN
=> Fixing a zh_TW translation text

isso/js/app/i18n/pt_PT.js
File missed the .js file extension.
The file contained a syntax error.
=> fix: pt_PT file mispelled name + syntax error

docs/_isso/sidebar-docs.html, docs/docs/extras/testing.rst
I ran into way too many `pkg_resources.DistributionNotFound` and `<parser>.NoSectionError` errors when trying to set up nosetests.
Prevent others from the same fate.
**EDIT:** Can be seen live using [this build artifact](https://156-203644882-gh.circle-artifacts.com/0/docs-html/docs/extras/testing/index.html)
=> [docs] Add 'Testing' section

docs/_static/css/site.scss, docs/docs/configuration/client.rst, docs/docs/configuration/server.rst, docs/docs/extras/api.rst, docs/docs/extras/deployment.rst, docs/docs/index.rst, docs/docs/install.rst, docs/docs/troubleshooting.rst, docs/faq.rst, docs/index.html, docs/releasing.rst
Numerous improvements to docs, fix some mistakes cleanups, align with current Isso behaviour .
- index: Correct Isso's current size
- Clean up whitespace, add links to sections
- Remove py2 references
- troubleshooting: Correct 404 section
Isso returns 200 instead of 404 since https://github.com/posativ/isso/pull/565
- docs/index: [Mention more alternatives](https://164-203644882-gh.circle-artifacts.com/0/docs-html/docs/index.html#what-s-wrong-with-disqus)
Rising tide lifts all ships and such...
- troubleshooting: [Mention markup config](https://164-203644882-gh.circle-artifacts.com/0/docs-html/docs/troubleshooting/index.html#why-isn-t-markdown-in-my-comments-rendering-as-i-expect)
This question has popped up in https://github.com/posativ/isso/issues/677
- faq: Cleanup - remove empty link …
=> [docs] Improve docs, cleanup, align with current version

.gitignore, Dockerfile, Makefile, docs/docs/install.rst, isso/js/.bowerrc, isso/js/build.count.js, isso/js/build.embed.js, isso/js/config.js, package.json, setup.cfg
Replace bower as well as global npm package installations in Dockerfile with a plain `package.json` that is used to configure what `npm install` will install. This avoids a dependency on bower which was deprecated in 2017 and hopefully makes it easier for others to build the JS frontend files.
There are lots of more things to cleanup in this area (jade got renamed to pug, requirejs could be replaced by webpack, just to name two outdated dependencies) so this is just a start.
=> Only use npm for managing JS frontend build dependencies

docs/docs/install.rst, setup.py
The minimum werkzeug version (1.0) requires Python 3 >= 3.5 so isso
has the same requirement too.
See also https://github.com/pallets/werkzeug/blob/dfde671ef969e27c7b14bd464688c009b34a7d2b/setup.py#L55 from werkzeug 1.0.0
=> Require Python >= 3.5

Makefile, docs/docs/install.rst
People should not be forced to install nodejs & npm just to contribute to docs.
sassc produces virtually identical output to node-sass; with `precision` set to "5", the output is **identical**.
node-sass wastes a lot of space and pulls in a total of 195 (mostly untrusted!) packages.
```
$ du -hs --apparent-size ~/.npm/node-sass/ ~/.cache/node_modules/
3,3M	/home/user/.npm/node-sass/
15M	/home/user/.cache/node_modules/
```
`sassc` is a couple of kilobytes, including ~3MB for `libsass`.
`sassc` is also faster by a lot, which makes live-reloading much less annoying:
```
hyperfine 'sassc --precision 5 docs/_static/css/site.scss docs/_static/css/site.css'
Benchmark #1: sassc --precision 5 docs/_static/css/site.scss docs/_static/css/site.css
Time (mean ± σ):      15.8 ms ±   2.4 ms    [User: …
```
=> Swap node-sass for sassc, mention in docs

Makefile, docs/docs/install.rst
Since https://github.com/posativ/isso/pull/695/ changed the way npm commands run, my docs updates in [#690](https://github.com/posativ/isso/pull/690/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R3) are outdated and should have been rebased.
Fix those.
=> Makefile, docs: Align with changes to npm handling

share/isso.conf
Misaka expects extensions and flags in `dashed-case` instead of the legacy `snake_case` as of version 2.0.
See https://github.com/FSX/misaka/blob/v2.1.1/misaka/utils.py#L15-L37
Also align "options" values with the defaults in `utils/html.py`.
=> share: isso.conf: Use dashed-case for misaka 2.0

CHANGES.rst, docs/docs/configuration/server.rst, isso/tests/fixtures.py, isso/tests/test_comments.py, isso/views/comments.py, share/isso.conf
Add new `samesite` option in `[server]` section to configure `SameSite` header for cookies.
As a fallback, use `local.host` to detect URL scheme and set `SameSite` to `None` (https) or `Lax` (http) accordingly.
Set `Secure` attribute in response header so that cookies will only be sent when requesting content from `https://`
URLs.
Fixes:
```
Cookie “isso-[id]” will be soon rejected because it has the “SameSite” attribute set to “None”
```
(werkzeug sets `SameSite` to `None` by default anyway)
**NOTE:** This change _might_ break quite a few local test setups!
Discussion: https://github.com/posativ/isso/issues/682
See: https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
and https://werkzeug.palletsprojects.com/en/1.0.x/http/#werkzeug.http.dump_cookie
---
Sidenote:
- …
=> Improve cookie SameSite/secure handling

CHANGES.rst, docs/docs/configuration/client.rst, isso/js/app/config.js, isso/js/app/text/css.js, isso/js/build.count.js, isso/js/embed.js
Instead of embedding isso.css inside the client javascript (which required an `style-src: unsafe-inline` CSP), fetch isso.css from `api.endpoint+"/css/isso.css"`.
Allow clients to override fetch location using `data-isso-css-url="https://comments.example.org/css/isso.css"`
Note: No modification needed for packaging since isso.css is already included via MANIFEST.in.
Fixes https://github.com/posativ/isso/issues/584
=> Serve isso.css separately instead of inline

isso/tests/test_comments.py, isso/views/comments.py
The `/id` GET endpoint is only used to retrieve the raw text of a comment to be edited. Being able to arbitrarily retrieve *any* comment through this endpoint is a potential privacy issue, since it allows a malicious actor to individually retrieve all comments from a website without knowledge of an existing thread URI.
This change requires that comment text retrieval has a valid edit cookie.
Fixes #679
=> Require an edit cookie to be able to view a comment to be edited.

isso/js/admin.js
save comment innerHTML under `elt.dataset['originContent']`, and restore it if edit action was canceled.
=> admin: restore comment content after cancel edit

README.md, docs/docs/install.rst
Reorder steps so that js files are generated before `python setup.py develop`.
Clarify that isso should be installed in editable mode when installed from source.
Clarify that sphinx is needed for docs, and only for docs.
Clarify that npm is definitely required.
Isso requires python 3.5 now.
=> docs: install: Reorder Install from source, py3.5

isso/__init__.py, isso/utils/__init__.py, isso/utils/hash.py, isso/wsgi.py, tox.ini
Since 3e3ee8b, werkzeug is required in version 1.0 or above
Also align deps in `tox.ini` with the ones in `setup.py`
=> Remove legacy werkzeug support

isso/css/admin.css, isso/templates/admin.html
Also update `admin.css` so that lines get wrapped
Note that `document.getElementById().textContent()` already overlooks the `<pre>` tags, so there is no need to strip them when using [send_edit()](https://github.com/posativ/isso/blob/5655f194b311c50126713e6f40440e7f89be6479/isso/js/admin.js#L92).
This is a dirty fix, but adding the client-side `contenteditable` mechanism here is something I'm not prepared to do. If anyone wants to pick this up, feel free to do so!
=> Use <pre> for comments in admin area

setup.py
Make package builds via setuptools automatically trigger building of
merged & minified JS assets.
This fixes installing isso from source when using `pip install` as long
as both the python and node requirements are met. It also ensures that
`setup.py` commands like `build` or `bdist_wheel` create archives that
contain generated JS code.
=> Build JavaScript files during python package build

isso/tests/test_html.py, isso/utils/html.py
As of version 0.12.2, Isso uses misaka 2.0 to render markdown. Misaka 2.0 uses `dashed-case` instead of `snake_case` for options.
Normalize passed extensions to dashed-case to avoid mistakes.
Note: Flags have only been around in Isso with misaka 2.0, so I hope users did not use dashed case with them.
=> utils: html: Normalize misaka extensions

Dockerfile
I don't know what the purpose of that `TOX_ENV` value was, but it seems to do the trick.
=> Dockerfile: Set TOX_ENV to use artifacts from nodejs build instead of building inside Python container (fixes #759)

isso/js/embed.js
`$(...)` returns `null` when the selector matches no element, and thus `$(...).length == 0` should not be used.
Fixes #306
=> Avoid TypeError when #isso-root is not in the DOM

isso/config.py, isso/tests/test_config.py, isso/tests/test_utils_hash.py, isso/utils/parse.py
Do not attempt to use python string interpolation on values.
This is especially important for parsing passwords that might contain '%'
<strike>Strip single and double quotes from values. This might help with people who try to supply their admin password surrounded in quotes.</strike> (Edit: removed)
See: https://docs.python.org/3.9/library/configparser.html#configparser.ConfigParser
Also adjust tests accordingly and add new test case for strings which should not be interpolated.
This avoids errors such as the following:
```
configparser.InterpolationSyntaxError:
'%' must be followed by '%' or '(', found: '%!...@c...!Cjq'
```
Fixes https://github.com/posativ/isso/issues/763
---
I also came across this while looking through the code:
treewide: Remove remaining py2 u-String usage
In python3, …
=> config: Disable interpolation of values

CHANGES.rst, docs/docs/configuration/client.rst, isso/js/app/config.js, isso/js/app/i18n.js, isso/js/app/isso.js, isso/js/app/utils.js
The code for setting `config["lang"]`, in `isso/app/config.js`,
assumes that browsers will always provide a value for
`navigator.language` and/or `navigator.userLanguage`.  Per bug #521,
this is not a safe assumption.
While I was attempting to fix this, I noticed that regional variants
of a language (`zh-TW`, `pt-BR`) were being handled in an ad-hoc,
unreliable manner.  I also noticed a new user-agent language property
[`navigator.languages`][] which more closely matches the semantics of
[`Accept-Language`][]—it would be good to support that.
This patch addresses all the above problems, as follows:
1. Add a new configuration property `data-isso-default-lang` that
specifies the language to use (instead of English) when the browser
*doesn’t* have a preference.
2. Document that we expect the …
=> Handle browsers with no navigator.language better (#521)

CHANGES.rst, docs/docs/configuration/client.rst, docs/docs/configuration/server.rst, isso/js/embed.js, isso/views/comments.py
Some settings (reply-to-self and require-email) always need to be set to the same value on server and client side for correct operation. This change removes the need for such redundant information by having the client read out those settings from the server.
According to the docs this should be true for require-author as well, but that settings doesn't seem to be implemented.
=> Have client read out shared settings from server

docs/docs/quickstart.rst
redo #768 
since code blocks don't unwrap lines, part of comment in config example is rendered as non-comment.
added `;` to start of line to fix that.
=> docs: quickstart: fix comment in sample config

setup.py
See discussion in https://github.com/posativ/isso/pull/697
Reason for revert: The change broke `sdist` (source distribution) installs (which will attempt to run `make` even when *installing*, but neither `Makefile` nor `package.json` are inlcuded in the tarball (see `MANIFEST.in`), so the command will fail.
=> Revert "Build JavaScript files during python package build"

isso/views/comments.py
The item check should happen before we try to access
the value not after otherwise it results in a backtracke like this:
gunicorn[441]: 2022-02-17 20:46:52,526 ERROR: GET /id/2038/delete/XXXXXXXXXXXX
gunicorn[441]: Traceback (most recent call last):
gunicorn[441]:   File "/opt/isso/lib/python3.6/site-packages/isso/__init__.py", line 150, in dispatch
gunicorn[441]:     response = handler(request.environ, request, **values)
gunicorn[441]:   File "/opt/isso/lib/python3.6/site-packages/isso/views/comments.py", line 635, in moderate
gunicorn[441]:     thread = self.threads.get(item['tid'])
gunicorn[441]: TypeError: 'NoneType' object is not subscriptable
Now we return a item NotFound instead.
Signed-off-by: fliiiix <hi@l33t.name>
=> comment moderation fix item value check

isso/css/admin.css, isso/js/admin.js, isso/templates/admin.html
Use a `<textarea>` element to let the user properly edit comments, where `contenteditable` was poorly suited for multi-line input.
---
If anyone has a cleaner solution, go for it.
This is my stopgap solution to make comment editing in the admin work again (which got bungled by the combination of https://github.com/posativ/isso/pull/470 and https://github.com/posativ/isso/pull/604, where currently the edited content is wrapped in unwanted literal `<pre>` tags)
=> [UGLY] admin: Use textarea for comment editing

README.md, setup.py
This allows for more information by embedding the README at https://pypi.org/project/isso/ as a "Project Description".
~~Reasoning: Use absolute link to allow embedding the rendered README on pypi (where the relative-path LICENSE is not available).~~
=> setup.py, README: Generate proper Project Description for PyPi

CONTRIBUTORS.txt, isso/tests/test_comments.py, isso/views/comments.py
Things this PR addresses:
* Replace Yo response from moderation with a more appropriate response
* Add tests for moderation
* Add tests for unsubscribe and fix doc string
Contributes to #755
=> views: moderation: Add unit tests, proper response instead of "Yo", apiDoc clarifications

isso/__init__.py, isso/run.py
gunicorn is not using main() it uses make_app via run.py.
Because of that we should check for the config file inside
make_app.
This is probably also true for other deployment options.
=> __init__.py: Fix config startup check

.github/workflows/documentation.yml, .github/workflows/pythonpackage.yml
GitHub runners should have pretty recent caches, no need for
this
Since python version in "setup-python" action is already 3.x, no need to specify "pip3"
Generate ready-to-install source distribution `sdist` packages and upload them using GitHub actions.
Before uploading, test if packages are actually installable.
Utilize heavy caching for CI run speedup.
=> GitHub Actions: Optimize actions, cache, upload artifacts

isso/js/embed.js
This restores the behavior before #311
Closes https://github.com/posativ/isso/issues/815
Note: This is only a hotfix!
We should revisit the way the client code constructs the core postbox and comment elements since we're now much more dependent on the calls to fetch config from the server before rendering anything.
[This piece of documentation](https://github.com/posativ/isso/blob/13b8df02c96392db1195db2e713e6f47b06dcd7e/docs/docs/extras/advanced-integration.rst#asynchronous-comments-loading) is also no longer 100% accurate.
=> isso: js: embed: Insert Postbox before comments

.github/workflows/documentation.yml, .gitignore, Makefile, docs/_static/css/site.css
No one has touched those css files in years, and by removing `sassc` as a dependency, we can cut down some build time and setup complexity.
Also remove from GitHub Actions.
=> docs: Check in rendered SCSS

Makefile, contrib/import_blogger.py
- `contrib: import_blogger: Warn on missing feedparser`
- `Makefile: Run flake8 on contrib/ folder, too`
=> contrib: import_blogger: Warn on missing feedparser, run flake8 in contrib/ as well

docs/docs/quickstart.rst, docs/index.html, isso/demo/index.html
Add `<noscript>` tags with a warning that for comments to work, Javascript needs to be enabled.
If a browser has Javascript enabled (as almost all modern browsers do by default), the tags will be invisible to the user.
=> docs, demo: <noscript> to warn that JS is needed

docs/docs/index.rst
The list was quiet outdated with abandoned projects, so i updated it.
Also added link to a great overview with all known open source comment servers.
The link is quiet long and breaks the 80 chars convention. How to handle that?
A different option for the heading would be "Alternatives". Let me know what you prefer!
Builds correctly:
=> docs: update list of alternatives

docs/docs/install.rst
The AUR helper yaourt has been unmaintained for years, has bugs and is probably not compatible with the current version of pacman. Yaourt should therefore no longer be used.
Since there are many alternative AUR helpers and an installation is also possible without such a tool, I think we should not give an installation example.
=> Removes reference to unmaintained yaourt

isso/js/app/isso.js
The selector also needs the `isso-` prefix, else the DOM selection fails and the subsequent code gets a null obj, which then fails.
This was overlooked in 85f3954c80bc68feb0de23c186d06c716016faae
"js: app/isso: Prefix localstorage keys w/ isso-"
Fixes https://github.com/posativ/isso/issues/839
=> js: isso: Fix class selector for preview

Dockerfile
The [current `Dockerfile`](https://github.com/posativ/isso/blob/master/Dockerfile#L2) uses an outdated version of Debian which ships versions of `node` and `npm` that incompatible with some of the packages Isso requires.
Issues reported in https://github.com/posativ/isso/issues/836
Fix this by using newer base images which ship the required node/npm versions. As a side benefit, Alpine Linux images are smaller, thus resulting in faster build times (less time required to pull) and a smaller generated docker image for Isso.
=> Dockerfile: Use Alpine base images, optimize process

.github/workflows/javascript-client.yml, isso/js/jest-integration.config.js, isso/js/jest-unit.config.js, isso/js/tests/integration/puppet.test.js, isso/js/tests/unit/config.test.js, isso/js/tests/unit/isso.test.js, isso/js/tests/unit/utils.test.js, package-lock.json, package.json, share/isso-dev.cfg
This PR adds end-to-end tests on top of https://github.com/posativ/isso/pull/801.
- **[Jest](https://jestjs.io/)** is a Javascript testing framework. It is mainly used here for unit tests.
- **[Puppeteer](https://github.com/puppeteer/puppeteer)** is a way of having a (headless) browser available for testing (via "browser instrumentation") and to simulate a user clicking on a link, pressing keys or manipulating DOM elements.
The `puppeteer` integration into `Jest` is done via the [jest-puppeteer](https://github.com/smooth-code/jest-puppeteer) plugin, as recommended in [Jest: Using with puppeteer](https://jestjs.io/docs/puppeteer).
**Note:** Installing `puppeteer` via npm **auto-downloads** an instance of Chromium into `node_modules/puppeteer/.local-chromium`, which is around **400MB** …
=> Add puppeteer end-to-end integration test

.dockerignore, .github/workflows/docker-compose.yml, docker-compose.yml, docker/Dockerfile-js-puppeteer, docker/Dockerfile-js-testbed
This will run e2e tests on every push and PR.
To be used with:
```sh
$ docker compose build [images...]
$ docker compose up -d
```
Documentation to follow.
One base image containing downloaded puppeteer chromium
binary (~400Mb), one testbed image to run the actual tests
This will speed up docker builds as the "build context" to
send to the daemon is now smaller.
=> [ci] [docker] Use docker for e2e, client testing, add docker-compose file

.github/workflows/documentation.yml, Makefile, docs/_isso/layout.html, docs/_isso/page.html, docs/_isso/search.html, docs/_isso/searchbox.html, docs/_isso/sidebar-docs.html, docs/_static/css/site.css, docs/_static/css/site.scss, docs/community.rst, docs/conf.py, docs/docs/index.rst, docs/index.html, docs/news.rst, docs/releasing.rst, docs/theme-testing.rst
(Such as missing table of contents entry)
Search was showing no context around items, only titles. To fix this, a block with `role="main"` had to be introduced at the correct location.
While at it, also make the "Edit on GitHub" link a macro and fix associated styling.
Only meant for maintainers
This gets rid of some warning pages. These pages are either included via the navbar or are not supposed to be rendered at all, so the warnings were superfluous.
=> docs: theme: Rework sidebar internals, fix search, error-on-warn, minor

docs/community.rst, docs/docs/contributing/documentation.rst, docs/docs/guides/tips-and-tricks.rst, docs/docs/guides/troubleshooting.rst
Wiki pages formerly under https://github.com/posativ/isso/wiki consolidated into docs
- More syntax suggestions
- Move admon down; rm done items
- Add headings section, shellcode
=> docs: Expand community & Writing docs pages, import wiki articles

docs/_static/css/site.css, docs/_static/css/site.scss, docs/docs/contributing/documentation.rst, docs/docs/contributing/index.rst, docs/docs/reference/client-config.rst, docs/docs/reference/server-config.rst, docs/docs/technical-docs/testing-client.rst, docs/docs/toc.rst, isso/isso.cfg
Will be evenly distributed into two columns, easing readability and taking up less space
Style `versionchanged`, `versionadded`, deprecated` directives to display e.g. "Changed in 0.12.6" with a slight yellow background.
Style definition lists to that titles stick out more.
Some sections were a bit out of date or did not convey the intent to users properly.
Also correct styling (many markdown-style single backticks where reST needs double ones) and add some more structural elements.
- `isso: isso.cfg: Add link for misaka exts`
- `docs: contrib: More links, clarification`
- `docs: toc: Remove superfluous file ext`
- `docs: css: Do not vertically center hlist items`
=> docs: Document snapshots, add "New in version x", def.-list styling, better config options documentation

isso/__init__.py
Fixes #585
This restores the behavior as was documented in the server config docs, i.e. makes it possible to use `ISSO_SETTINGS=share/isso-dev.cfg isso run`.
This used to fail as `ISSO_SETTINGS` was only read by WSGI invocations of `isso.dispatch` or `isso.run`
---
Ping @jwatt
=> [server] isso/init: Log paths at start, error if not found; ISSO_SETTINGS takes precedence over -c flag

isso/migrate.py, isso/tests/disqus.xml, isso/tests/test_migration.py
Fixes https://github.com/posativ/isso/issues/728
To verify:
```sh
isso -c share/isso-dev.cfg import --empty-id -t disqus isso/tests/disqus.xml
```
This one will fail by default without `--empty-id`:
```
Isso couldn't import any thread, try again with --empty-id
```
The addition of a thread with an empty id in `disqus.xml` necessitates adjusting the unit tests to work around this.
=> isso: migrate: Workaround empty Disqus ids/titles

CHANGES.rst, docs/docs/reference/client-config.rst, isso/js/app/config.js, isso/js/app/templates/postbox.js, isso/js/tests/unit/postbox-reply-notif.test.js
Fixes #837 
Configure by setting `data-isso-reply-notifications-default-enabled` to `"true"` in the client settings. If set to true, then the checkbox for enabling reply notifications will be checked by default:
=> [client] js: Support enabling reply notifications checkbox by default

isso/js/app/template.js, isso/js/tests/unit/__snapshots__/template-comment-newlines.test.js.snap, isso/js/tests/unit/template-comment-newlines.test.js
Non-discriminatory newline stripping would wrongfully collate pre-formatted (code) blocks.
The newline stripping/trimming was introduced as a workaround because at the time, templates were written in ES6 template literals (`${foo}`) and left a lot of newlines in rendered HTML output, which lead to failures to convert text to DOM elements using the `htmlify` helper.
These templates ended up being replaced by ES5 plain string concatenation, which no longer requires the workaround.
Fixes https://github.com/posativ/isso/discussions/856
=> js: template: Do not strip newlines

docs/_static/css/site.css, docs/_static/css/site.scss, docs/docs/reference/markdown-config.rst, docs/docs/reference/server-config.rst, docs/docs/toc.rst
=> [docs] Add Markdown rendering explanation, refs, more styling of tables and other elements

CHANGES.rst, isso/isso.cfg, isso/utils/html.py, share/isso-dev.cfg
The commit 72e624bf6aeaeffa03a26f7d258561269ae54eec "share: isso.conf: Use dashed-case for misaka 2.0" removed the misaka extension `no-intra-emphasis`, mistakenly. Add it back again.
Also correct the (mostly unused) default options in utils/html.py and add a CHANGES entry.
The `superscript` extension was enabled by default and it might have been confusing for commenters as well as admins why their x^2 did not render correctly.
This is just a minor qualify-of-life improvement. If admins choose to enable the (not-enabled-by-default) `<img>` tag, they most likely also want `src=...` to be enabled as well.
=> [server] Re-enable no-intra-emphasis Markdown ext, allow sub/sup elms by default, src if img

README.md
Add more sections, with more links, small install guide, add new screenshot.
This should make the README more inviting to people browsing GH - and also PyPI, as the README is also automatically uploaded there.
Live preview @ [TestPyPI](https://test.pypi.org/project/isso-testpypi/)
Screenshot used:
=> README: Include more information, new screenshot

CHANGES.rst, docs/docs/reference/client-config.rst, isso/css/isso.css, isso/js/app/config.js, isso/js/app/i18n/en.js, isso/js/app/isso.js, isso/js/app/templates/comment.js
Fixes #82 
- Page author's comments will have a different background
- Their name will have a different color
- Configured using `data-isso-page-author-hashes` field in the `<script>` tag; this can include multiple hashes.
- Add matching CSS rules, and change the margin/padding rules a bit to make `.isso-text-wrapper` take up the comment's size
- Move `.isso-follow-up` div outside of `.isso-text-wrapper`
Screenshot at the bottom of this description.
I moved the `.isso-follow-up` div to be outside of `.isso-text-wrapper` (so it is instead a direct child of `.isso-comment`). Then I gave the background color to the `.isso-text-wrapper`. Without this change, if someone else replies to a comment by the page author, their comment still has the background. This is because the …
=> Make it possible to identify the page author's comments

isso/css/isso.css
Before this change, on Chrome and Safari (but not Firefox), the `svg` inside `.isso-avatar` has a size of 0 by 0 pixels. Not sure why it worked on Firefox, but this makes sense because svg's have no native size, and since there was no minimum size specified, it defaulted to 0.
Instead of just setting `width` to `48px`, I set it to `100%` and left `max-width` set to `48px`. [It should be better practice this way](https://css-tricks.com/tale-width-max-width/).
I am wondering if setting `height` is a good idea, since it seems to have no effect. I kept it in just because it's clearer.
=> [client] Fix avatar sizing on Chrome & Safari

docs/docs/guides/tips-and-tricks.rst, isso/css/isso.css, isso/js/embed.js, isso/js/tests/integration/highlight-comments.test.js, isso/js/tests/integration/puppet.test.js, package.json
=> [client] Highlight linked comments to identify them

CHANGES.rst, isso/js/app/i18n.js, isso/js/app/i18n/de.js, isso/js/tests/unit/postbox-labels-optional.test.js
Enable Turkish translations - They were previously added, but not loaded anywhere.
Also add some missing German strings.
Clean up and sort `pluralforms` (`oc` entry was a duplicate of `fr`).
=> [client] i18n: Enable Turkish translations, add missing German strings

.github/workflows/python-tests.yml, CHANGES.rst, isso/views/comments.py
Add `/config` endpoint which returns the same data as the `config` object of the `/` GET endpoint. This endpoint is unused by the current client but useful for development and will be utilized in the future.
A partial re-send of https://github.com/posativ/isso/pull/821
This PR prepares work for fetching the configuration from a dedicated endpoint *before* fetching any comments or inserting a postbox. Instead of fixing all the issues that pop up in #821 immediately, merge this partial (currently unused) feature already and then start work on ironing out client bugs.
=> [server] Add /config endpoint

isso/js/app/count.js
=> js: count: Don't send `/count` request if there are no counters

isso/js/jest-integration.config.js, isso/js/jest-puppeteer.config.js, isso/js/jest-unit.config.js, isso/js/tests/integration/puppet.test.js
- js: test/integration: Test API directly
- js: test: Add boilerplate jest-puppeteer conf  
Currently unused, but useful for quick debugging & adjustments during E2E testing.
Improved test coverage
=> [client] js: test/integration: Test API directly

CHANGES.rst, isso/core.py, isso/utils/cache.py, setup.py
Instead of relying on flask-caching and its dep cachelib, import a trimmed-down version into the repo as `utils/cache.py`.
While seeing https://github.com/pallets-eco/flask-caching/pull/352 that currently breaks Isso, it became apparent that `Flask-Caching` has grown way too large and has gained dependencies of its own.
Initially, Isso depended on `SimpleCache` and `NullCache` from `werkzeug.contrib`, which meant that it didn't have to import any new dependencies. In a later version, caching was removed from werkzeug and instead pushed into its own package, which Isso then had to import.
With the newest release of `Flask-Caching`, there's now a hard dependency on `cachelib` as well, in addition to `flask`.
Isso only uses `get()`, `set()` and `delete()` cache functions and only for …
=> [server] core: Replace flask-caching dependency with drop-in

isso/tests/test_comments.py, isso/views/comments.py
Previously, if a dict item was supplied by the JS client but contained an invalid value such as `null`, the server would only check if the dict key was provided, not if its value was falsy.
```python
>>> mydict = dict(a='hi', b=None)
>>> 'b' in mydict
True
>>> 'b' not in mydict
False
```
Instead, use `.get()` and check if the value is empty. Then, for instance, attempt to parse thread uris if payload title is invalid instead of simply accepting `null` as thread title.
Also add a test to check this behavior.
Fixes: https://github.com/posativ/isso/issues/874
=> [server] views: comments: Check using get(), not 'in'

CHANGES.rst, docs/docs/reference/server-config.rst, isso/config.py, isso/tests/test_guard.py
Fixes https://github.com/posativ/isso/issues/498
Starting in 0.13, a trailing slash in `[server] public-endpoint` is now discouraged and throws a warning.
---
Ideally, we should strip the trailing slash automatically from *any* config value that contains a URL, and be consistent with examples in docs, example config files.
=> [server] Strip trailing slash from public-endpoint, disallow trailing slash

CHANGES.rst, isso/db/comments.py, isso/tests/test_comments.py
- db: comments: Constrain parent of new comments
- tests: Add test for invalid comment parents 
Fixes #765
=> [server] db: comments: Constrain parent of new comments 

Dockerfile, MANIFEST.in, Makefile, README.md, contrib/isso.sample.cfg, docs/_static/css/site.css, docs/_static/css/site.scss, docs/docs/contributing/documentation.rst, docs/docs/contributing/index.rst, docs/docs/reference/client-config.rst, docs/docs/reference/installation.rst, docs/docs/technical-docs/testing-client.rst, docs/docs/technical-docs/testing-server.rst
- contrib/docs: Add live rST editor link, nit
- [nit] client-config: Mark strings with quotes
- testing-client: Update make docker cmds
- css: Indent ordered lists as well, cleanup
- contrib: More purpose-oriented TOC
- contrib: Add commit msg examples, checklist
- contrib/docs: Mention commento contrib, nits
- [nit] test-server: Correct make command
Those files allow for de-obfuscating minified webpack-assembled bundles and tracing function calls back to the source files when used in browser debuggers.
Marking /admin and /demo endpoints as private is semantically correct, but since these docs are aimed at developers anyway, document them in any case.
To be used as a base for e.g. Docker instructions.
Mention the official image and be a bit more clear about config requirements.
=> [docs] Polish contribute page, css list nits, client-config & docker fixes

isso/css/isso.css
css: Reduce specificity of selectors, cleanup, order 
Contributes to https://github.com/posativ/isso/issues/859
=> [client] CSS cleanup

CHANGES.rst, isso/migrate.py, isso/tests/test_migration.py, isso/tests/wordpress.xml
WordPress renders a single newline in a comment as a <br> tag, but Isso renders a single newline in the comment as a single newline in the HTML. This is rendered the same as if it was a space, all text on one line.
To fix, detect single newlines when importing WordPress comments and convert to a line break in Markdown. Add a test for this also.
Example, this WordPress comment (as shown in CDATA of XML export):
> First line of comment.
> Second line of comment.
Renders in WordPress as:
> First line of comment.<br>Second line of comment.
But renders in Isso after import as if it was:
> First line of comment. Second line of comment.
After this commit is applied and comments re-imported, it renders as:
> First line of comment.
> Second line of comment.
- (N/A) (If docs changes needed:) I have …
=> migrate: Handle single newlines in WordPress comments as line breaks

Dockerfile
This change explicitly creates the volume mount directories in the docker image and gives them global write permissions (`1777`).
This allows the docker images to be use named/anonymous volumes (e.g `-v /db` or `-v isso-db:/db`) with non-root users (e.g. `--user=2000:2000`).
For example:
```
$ mkdir config
$ sed 's,comments.db,/db/\0,g' contrib/isso.sample.cfg > config/isso.cfg 
$ docker run --user 2000:2000 --rm --name isso -p 127.0.0.1:8080:8080 \ 
-v $PWD/config:/config -v /db ghcr.io/isso-comments/isso:0.13.0
Traceback (most recent call last):
File "/isso/bin/gunicorn", line 8, in <module>
sys.exit(run())
File "/isso/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
File …
```
=> Dockerfile: Explictly create volume paths and set permissions

isso/js/app/i18n.js
Fix error when certain translation not present.
When borwser's language is not English, and certain `msgid` dose not exist in target translation, we want provide the string in English, or `[?${msgid}]` format. But current implementation would just throw an error and interrupt the whole script, because `en` is not defined.
=> js: i18n: fix translation fallback to English

isso/ext/notifications.py
If using the uwsgi e-mail system, the attempt to do headers.encode() would cause an AttributeError if there were no headers. This pull request fixes this error.
```
2023-01-06 17:46:31,546 ERROR: POST /new
Traceback (most recent call last):
File "isso/__init__.py", line 152, in dispatch
response = handler(request.environ, request, **values)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "isso/views/comments.py", line 82, in dec
return func(self, env, req, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "isso/views/__init__.py", line 43, in dec
return func(cls, env, req, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "isso/views/comments.py", line 331, in new
self.signal("comments.new:after-save", thread, rv)
File "isso/ext/__init__.py", line 17, in __call__ …
```
=> ext.notifications: Avoid error if headers are None

docs/docs/technical-docs/testing-client.rst
Fix typo in Doc
What changes does this Pull Request introduce?
This fixes incorrect documentation for running unit test: `npm run test-unit` from `npm run tests-unit`
Why is this necessary?
Currently the doc is incorrect and will not run unit tests
=> docs: testing-client: Fix typo in make command

CHANGES.rst, isso/tests/test_comments.py, isso/views/comments.py, setup.py
Changed website validation to allow domain names containing umlauts
Resolves issue #951
=> Allow umlaut domains for website addresses

CHANGES.rst, isso/js/app/config.js, isso/js/app/i18n.js, isso/js/tests/unit/i18n-overrides.test.js
Differing internal representations of two-level language codes, e.g. `pt_BR`/`pt_PT` or` zh_CN`/`zh_TW`, would lead to inconsistencies when combined with overrides of i18n strings for templating.
E.g. setting` data-isso-lang=pt_BR` and `data-isso-postbox-text-text-PT_BR=foo` would result in an internal representation of `data-isso-postbox-text-text-pt-br` (note: lowercase) and thus user-supplied i18n strings not being applied.
To make this handling more robust, convert everything into lowercase and substitute underscores for dashes.
Fixes https://github.com/posativ/isso/issues/982
Add jest tests
=> js: Make language code handling more robust, add tests

isso/__init__.py
Add error message for improperly configured `server.listen`
Otherwise the error message is quite cryptic, what I saw was ultimately:
```
AttributeError: 'int' object has no attribute 'strip'
```
=> Add error message for improperly configured server.listen

docs/docs/reference/client-config.rst
- Remove `data-isso-id` from script tag options: `data-isso-id` can only be set within the `#isso-thread` tag; values inside the `<script>` tag will be ignored.
See https://github.com/posativ/isso/blob/0.13.0/isso/js/embed.js#L125
- Some minor formatting improvements for the Client Config page
Solves https://github.com/posativ/isso/issues/924
=> docs: Remove data-isso-id script tag reference, slighly improve wording

.github/workflows/docker-build.yaml
This PR adds an automated docker build using GH actions.
Images are build automatically for the following patterns:
- PR is opened/updated: builds and tags the image but does not push it to the registry (this is done to verify a successful build; [example build](https://github.com/janw/isso/actions/runs/6102764489))
- Push to `master` (i.e. merge a PR): build and tag image with `:latest` ([example build](https://github.com/janw/isso/actions/runs/6102803470))
- Push a new tag (i.e. release new version): build and tag with
- major version only (i.e. `:0`), and major+minor version (i.e. `:0.14`) ([example build](https://github.com/janw/isso/actions/runs/6102878038/job/16562257652))
- full version (i.e. `:0.14.1-post.0`) ([example build](https://github.com/janw/isso/actions/runs/6102861527)) …
=> Add docker-build workflow (#942)

CHANGES.rst, isso/tests/test_html.py, isso/utils/html.py
- Enhanced the `Sanitizer` class in `isso/utils/html.py` to prevent the automatic creation of invalid links by:
modifying the `set_links` function to reject new links, allowing only existing links to be modified. This change addresses the issue where text could be misinterpreted as a domain name, leading to the creation of invalid links.
- Updated tests in `isso/tests/test_html.py` to include new cases that ensure:
text that could be misinterpreted as links, such as 'ld.so' and file paths, are not automatically converted into links.
Fixes https://github.com/posativ/isso/issues/557
=> isso: html.py: Prevent auto creation of invalid links in comments

CHANGES.rst, isso/tests/test_html.py, isso/utils/html.py
In `html.py`:
- Updated the HTML sanitization process to allow specific attributes for different tags.
- Modified the `blockcode` function to add `'language-'` prefix to the class attribute for code tags, improving compatibility with Highlight.js.
Closes https://github.com/isso-comments/isso/issues/177
=> isso: html.py: Make <code class="language-$lang"> for syntax highlighting

CHANGES.rst, isso/css/isso.css
Added CSS variables to improve theme customization and organization in `isso.css`.
Closes https://github.com/isso-comments/isso/issues/655
=> css: Add CSS variables for better organization and flexibility

CHANGES.rst, isso/css/admin.css, isso/db/comments.py, isso/templates/admin.html, isso/views/comments.py
Added support for searching comments by URL in the admin interface. This includes changes to the backend to handle comment URL queries and extract comment IDs, and frontend changes to add a search input to the admin page.
- Updated admin CSS to include styles for the new search input and button.
- Modified the fetchall method in comments.py to accept an optional comment_id parameter for fetching a specific comment by ID.
- Updated the admin HTML template to include a search form that allows inputting a comment URL for search.
- Updated the admin method in views/comments.py to handle the comment_url query parameter, parse the URL to extract the comment ID, and fetch the corresponding comment.
Closes https://github.com/isso-comments/isso/issues/642
=> admin: Add support for comment search by URL

docs/docs/contributing/infrastructure.rst, docs/docs/toc.rst
Try to codify the new reality of the project since Martin stepped down and make sense of all the informal or mostly-one-off processes we are currently running.
I've also created [isso-demo-config](https://github.com/isso-comments/isso-demo-config) and [isso-marketing-material](https://github.com/isso-comments/isso-marketing-material) as well as linked [ansible-role-isso](https://git.ix5.org/felix/ansible-role-isso) to coincide with this PR.
Brought about by recent events, I thought about the nature of maintainership a bit and realized that we have a) a pretty significant bus factor and b) our infra could be a bit opaque to newcomers. Collecting all the information and writing it down in one place also might help highlight a few blind spots and areas for improvement.
=> docs: Document Isso Project Infrastructure

CHANGES.rst, isso/js/embed.js, isso/tests/test_comments.py, isso/views/comments.py
Changes to properly count hidden comments when calculating the total number of comments.
- `isso/views/comments.py`: The calculation of total_replies is modified. Instead of directly assigning the value of reply_counts[root_id] to total_replies, it now calculates the sum of all values in reply_counts if root_id is None, otherwise it assigns the value of reply_counts[root_id].
- `isso/js/embed.js`: The redundant incrementation of the count variable with comment.total_replies was removed.
- `isso/tests/test_comments.py`: Several assertions are added to various test cases to check the value of total_replies in the response data.
Fixes https://github.com/isso-comments/isso/issues/448
- Before fix
- After fix
=> comments: Fix total comments count calculation

CHANGES.rst, isso/js/app/config.js, isso/js/tests/unit/config.test.js
Replace escaped newline characters in data-isso attribute values with actual newline characters to ensure correct parsing and display.
Fixes https://github.com/posativ/isso/issues/912
Example of a non-working configuration from a related issue:
```
<script data-isso="//comments.test.com/" src="//comments.test.com/js/count.min.js"
data-isso-num-comments-text-en="One comment\n{{ n }} comments"></script>
```
=> js: config.js: Fix newline character handling in data-isso-* i18n strings

.github/workflows/docker-build.yaml, CHANGES.rst, Dockerfile, Makefile, README.md, docs/docs/reference/installation.rst
- `:latest` is now used for auto-pushed images off of `master`, while `:release` will follow the latest tagged stable release.
- Use `org.opencontainers.*` docker `LABEL` metadata to connect images to our GitHub source
https://github.com/isso-comments/isso/issues/1012
=> Docker, docs: Document and implement changed image tagging policy

CHANGES.rst, isso/__init__.py, isso/ext/notifications.py
When the server is configured with `general.notify = stdout` and `moderation.enabled = true`, new comment activation links are not added to Stdout.
I modified the Stdout class to log a direct link to a new comment, as well as links to delete or activate the comment.
Fixes https://github.com/isso-comments/isso/issues/138
=> ext: notifications: Add link logging for management of new comments in Stdout

.dockerignore, docker-compose.yml, isso/js/tests/integration/puppet.test.js
- Check whether the comment _really_ got created and otherwise fail faster in the integration test before `PUT` request
- Improve a few documentation comments
End-to-end tests have been flaky when run in the dockerized environment. This seems to fix it locally for me, using the following steps:
```sh
make docker
docker compose up -d
make docker-js-integration
```
=> docker, ci: Make e2e tests less flaky

CHANGES.rst, isso/css/admin.css, isso/db/comments.py, isso/js/admin.js, isso/templates/admin.html, isso/views/comments.py
The main theme of the changes is to enhance the comment search functionality in the admin interface. The changes allow searching for comments not only by comment URL but also by thread URL.
- https://github.com/isso-comments/isso/issues/642
- https://github.com/isso-comments/isso/pull/1000
=> admin: Add support for comment search by Thread URL in admin interface

CHANGES.rst, isso/__init__.py
This change propagates the log format formerly only for werkzeug to all isso logs.
Having date and time information as well as the loglevel should satisfy most users instead of the more complicated solution in https://github.com/isso-comments/isso/pull/976
=> Change logging to include datetime and loglevel

CHANGES.rst, isso/db/__init__.py, isso/db/comments.py, isso/tests/test_db.py
This update introduces a schema migration to version 4 for the database, focusing on enhancing the 'comments' table. This ensures that the 'text' field in the 'comments' table will always have a value, which improves data consistency and integrity.
The key changes:
- Incrementing the database schema version from 3 to 4.
- Updating the "text" field in the "comments" table to be NOT NULL by setting empty strings for any NULL values.
- Creating a new table, "comments_new", with a NOT NULL constraint on the "text" field and then migrating data from the old "comments" table to this new table.
- Renaming the original "comments" table to "comments_backup_v3" for backup purposes and renaming "comments_new" to "comments" to finalize the migration.
- The migration process includes transaction …
=> db: Make 'text' field in 'comments' table NOT NULL and handling data migration

.github/workflows/python-package.yml, .github/workflows/python-tests.yml, CHANGES.rst, Dockerfile, Makefile, docker-compose.yml, docs/docs/contributing/documentation.rst, docs/docs/reference/installation.rst, docs/docs/technical-docs/testing-client.rst, docs/docs/technical-docs/testing.rst, setup.py
Compatibility for Python 3.12 and a few stray nits
* Mentions needed `virtualenv` package in docs, make pip and virtualenv related commands more consistent
* Require `setuptools` in `setup.py` (mostly because of `pkg_resources`)
* docker: Use buildkit in another instance of the `Makefile`, remove version from `compose` file, improve `Dockerfile` formatting
* Mark Python 3.12 support in `setup.py` and use it in `Dockerfile`, GitHub Actions
Python 3.12 changes: [What's new](https://docs.python.org/3/whatsnew/3.12.html)
> [gh-95299](https://github.com/python/cpython/issues/95299): Do not pre-install `setuptools` in virtual environments created with `venv`. This means that `distutils`, `setuptools`, `pkg_resources`, and `easy_install` will no longer available by default; to access these run …
=> Python 3.12 compatibility; docker, venv/virtualenv

isso/tests/test_comments.py, isso/views/comments.py
- [-] (If docs changes needed:) I have updated the **documentation** accordingly.
- [-] I have added an entry to `CHANGES.rst` because this is a user-facing change or an important bugfix
The same `API.verify()` method is called when creating a new comment or editing existing ones.
Previously, `API.verify()` was only called during comment creation.
In order to face spammers, I use a custom `API.verify()` method on my isso instance to forbids URLs in comments
( while waiting for some other spam-control mechanism to be implemented in isso maybe on day, _cf._ https://github.com/isso-comments/isso/issues/941 )
On my instance, I have seen spammers creating empty comments and then editing them to insert URLs.
This PR ensures that the same rules defined in `API.verify()` are applied during all …
=> Fix: now applying the same verifications when creating or editing comments

CHANGES.rst, isso/css/admin.css, isso/js/admin.js, isso/templates/admin.html
Fixes #552
Adds a logout button to the header, in the top right.
Tasks:
=> admin: Add log out button

isso/views/comments.py
- [NA] (If adding features:) I have added tests to cover my changes
- [NA] (If docs changes needed:) I have updated the **documentation** accordingly.
- [NA] I have added an entry to `CHANGES.rst` because this is a user-facing change or an important bugfix
Previous to this one-line fix, the following error message could be returned:
URI does not exist %s
Now the error message containes the actual URI:
URI {uri} does not exist
To help debug problems! 🙂
=> Fixing error message: URI {uri} does not exist

CHANGES.rst, docs/docs/reference/server-config.rst, isso/config.py, isso/tests/test_config.py
Adds support for using environment variables in the Isso configuration file (isso.cfg). Environment variables can be referenced using the `$VAR_NAME` or `${VAR_NAME}` syntax.
This allows users to keep sensitive information, such as passwords, out of the configuration file itself by referencing environment variables.
- Updated `IssoParser` to support environment variable substitution.
- Enhanced documentation to include details on using environment variables in the configuration file.
- Added unit tests to verify the functionality of environment variable substitution in `IssoParser`.
Closes https://github.com/isso-comments/isso/issues/397
=> isso: config: Add support for environment variables in config

.github/workflows/e2e-tests.yml, .github/workflows/javascript-client.yml, .github/workflows/python-package.yml
Update the GitHub actions workflows to use the v4 variant of `actions/upload-artifact`.
upload-artifact@v3 has been sunset and will result in CI failures.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> .github: Update actions to upload-artifact@v4

CHANGES.rst, isso/views/comments.py
- Update API documentation to include optional `title` parameter for new comments.
- Change error handling: when creating the first comment for a new thread, return a `BadRequest` if the URI is inaccessible and no title is provided, prompting the user to supply a title.
Fixes https://github.com/isso-comments/isso/issues/1055
=> Document title parameter and improve error handling for /new API
