isso-comments/isso

isso/utils/__init__.py
I just moved my comments from my Wordpress blog to Isso and some of them had some weird things going on in the IP address field. This should fix it.
=> Catch exception in anonymize function

isso/js/app/i18n.js, isso/js/app/i18n/zh_CN.js
=> add: zh_CN Translation

isso/js/app/i18n/zh_TW.js
Hello,
I added a zh_TW translation file, please take a look if the file is OK.
Thank you for create Isso, it is awesome!
=> Added zh_TW translation

docs/docs/configuration/client.rst, docs/docs/configuration/server.rst, isso/db/spam.py, isso/js/app/config.js, isso/js/app/isso.js, isso/tests/test_guard.py
I mirrored the way require-email worked.
=> Add an option for mandatory author (Fix issue #124)

isso/tests/test_comments.py, isso/views/comments.py
A simple endpoint for clients that want to show a preview of the comment to the user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/posativ/isso/254)
=> Preview endpoint

isso/js/app/globals.js
correct offset localtime for comments ago.
=> correct offset localtime for comments ago

docs/docs/install.rst
created a rc.d script for FreeBSD startup of isso within a jail or upon a regular host
=> added FreeBSD rc.d script

isso/js/app/i18n/da.js
Not much to say. I've added a da.js file that should hopefully do :)
=> Danish translation

isso/js/app/utils.js
=> display only complete units of time

isso/js/app/isso.js
=> Fix require-email setting

isso/js/app/i18n.js
Fixes issue documented [here](https://github.com/posativ/isso/pull/355#discussion_r152453699)
=> Put hu into correct alphabetical order

isso/ext/notifications.py
- Tested on version 0.10.6 on pypi, so it would be great if
someone can test it on the master version
=> A quick dirty fix of #401

isso/js/app/i18n/zh_CN.js, isso/js/app/i18n/zh_TW.js
There should be space between numbers and CJK characters.
Well, I added it.
=> i18n: add space between number and CJK character

isso/css/isso.css
It has been removed in 0211322915be.
=> css: remove CSS code for avatar in postbox

CHANGES.rst, CONTRIBUTORS.txt, isso/tests/test_html.py, isso/utils/html.py, setup.py
=> Upgrade to Misaka 2

isso/js/app/i18n/de.js
see <https://www.duden.de/rechtschreibung/E_Mail>
=> Fix spelling of "E-Mail" (german)

docs/docs/extras/deployment.rst
The examples for wsgi in the docs are out-of-date. This is basically just me copy-pasting `run.py` to the docs.
=> Update docs for mod_wsgi

isso/js/app/i18n/zh_CN.js, isso/js/app/i18n/zh_TW.js
=> i18n: zh_CN/TW translate for 'postbox-notification

isso/tests/test_html.py, isso/utils/html.py, setup.py, tox.ini
=>  Use bleach to sanitize HTML

isso/ext/notifications.py
This commit fixes an error occuring when isso sends out mail notifications via the uWSGI spooler.
See issue #492
=> Properly handle to field in mail notifications when using uWSGI spooler

docs/docs/configuration/server.rst
Idk maybe it would be possible to link it relativ but I didn't found out how it would work.
=> Consistency and link to client config

docs/docs/extras/deployment.rst
With these instructions I was finally able to deploy isso on a cheap Dreamhost shared hosting :-)
=> docs: update deployment info for FastCGI

isso/js/app/i18n.js, isso/js/app/i18n/pl.js
Update the Polish translation:
1. Add missing strings and fix "Preview"
2. Use full Polish plural forms (conditional taken from gettext)
3. Include Polish locale in output JS
=> Update Polish translation

isso/ext/notifications.py
=> Include user e-mails in admin notifications only

isso/ext/notifications.py
Fix for https://github.com/posativ/isso/issues/578
=> Set subject for notification about new comment, subject should not be empty

docs/docs/extras/deployment.rst, docs/docs/install.rst, docs/docs/man/index.rst, docs/docs/quickstart.rst, docs/docs/setup/multiple-sites.rst, docs/docs/troubleshooting.rst, docs/faq.rst
Minor grammar fixes and made sentence on line 14 easier to understand. 
Grammar fixes and other text fixes across multiple files.
=> Minor text imporvements to faq.rst

MANIFEST.in
Include admin.js in python package
=> FIX: include admin.js in Python Package

.travis.yml, isso/__init__.py, isso/core.py, isso/dispatch.py, isso/wsgi.py, setup.py, tox.ini
Fix compatibility with werkzeug 1.0.0. Fixes #611
=> Fix compatibility with werkzeug 1

CHANGES.rst, docs/docs/configuration/server.rst, isso/tests/test_html.py, isso/utils/html.py, share/isso-dev.conf, share/isso.conf
html: Add markdown render flag option
=> html: Add markdown render flag option

isso/js/app/i18n.js, isso/js/app/i18n/pt_BR.js
=> [i18n] Added the Brazilian Portuguese language

.travis.yml, Makefile, setup.py, tox.ini
=> Drop support for Python 2

contrib/dump_comments.py
_cf._ https://github.com/posativ/isso/issues/634
=> Adding contrib/dump_comments.py - close #634

isso/db/comments.py
I had an issue with my bloom filter, and those log messages helped me a lot to figure it out.
In the end I simply cleared them all:
```python
import sqlite3
from isso.compat import buffer
from isso.utils import Bloomfilter
bf = buffer(Bloomfilter(iterable=["127.0.0.0"]).array)
with sqlite3.connect('.../isso.db') as con:
con.execute('UPDATE comments SET voters=?', (bf, ))
```
=> Add warnings on Comments.vote failures

isso/__init__.py
...to take into consideration the `X-Forwarded-Prefix` HTTP header
=> Adding a [server] proxy-fix-enable-x-prefix configuration option

docs/_isso/sidebar-docs.html, docs/docs/extras/contribs.rst
_cf._ discussion in https://github.com/posativ/isso/issues/634
=> Adding docs/extras/contribs.rst

isso/core.py, setup.py
=> Fix #657 flask_caching 1.9 backend names

isso/js/app/i18n/tr.js
=> Add Turkish translation

docs/docs/install.rst
=> Fix dead links to init scripts

isso/tests/test_html.py, isso/utils/html.py
=> Add HTML escaping to code blocks

isso/utils/html.py
Make html.py pass flake8 code checking again.
=> Add missing whitespace after comma

Dockerfile
Use aliases when using `COPY --from` as suggested by hadolint for better understanding
=> fix: Dockerfile copy use aliases

.travis.yml, docs/index.html
Move the IRC channel to irc.libera.chat.
=> Move the IRC channel to irc.libera.chat

isso/js/app/i18n.js, isso/js/app/i18n/ko.js
=> Add Korean translation

isso/js/app/i18n/vi.js
Just added missing sentence for translation
=> Update Vietnamese translation

.github/workflows/pythonpackage.yml, setup.cfg, setup.py
=> Add a github action

.github/workflows/documentation.yml
Only runs on changes to `docs/**`.
=> .github: Add sphinx docs GH Action

CHANGES.rst, docs/docs/configuration/server.rst, isso/wsgi.py
Reason for revert: This feature never worked.
See discussion in #720
=> Remove ISSO_CORS_ORIGIN and references

docs/_static/css/site.css, docs/_static/css/site.scss, docs/community.rst, docs/docs/contributing/documentation.rst, docs/docs/contributing/index.rst, docs/docs/reference/installation.rst, docs/docs/technical-docs/client.rst, docs/docs/technical-docs/server.rst, docs/docs/technical-docs/testing-client.rst, docs/docs/technical-docs/testing-server.rst, docs/docs/technical-docs/testing.rst, docs/news.rst
Fill in a lot of missing pages and document testing practices extensively.
Related: https://github.com/posativ/isso/issues/797
@Guts might be happy that the "Contributing" section finally explains what changes are encouraged.
=>  docs [MAJOR]: Fill in community, testing, contrib pages, add news entries 

docs/docs/contributing/documentation.rst, docs/docs/contributing/index.rst, docs/docs/technical-docs/testing.rst, docs/docs/toc.rst
Add explanations on how to install and run Sphinx and how to write `reST`.
=>  docs: contrib: More links, explain building the docs, syntax

CHANGES.rst, isso/js/app/i18n.js, isso/js/app/i18n/uk.js
Added Ukrainian localization
Did i miss anything in the js code?
Ukrainian localization
War, fairness, making the experience easier for Ukrainians, pick whichever you like more.
=>  app: i18n: Added Ukrainian translation

CHANGES.rst, isso/ext/notifications.py
`EmailMessage` is a more modern interface and will enable header customization in future commits.
Fixes: https://github.com/posativ/isso/issues/467
To verify this change, set
```
notify = stdout, smtp
```
or
```
reply-notifications = true
```
and set up the `smtp` section with valid credentials.
=> [server] ext: notifications: Implement 'List-Unsubscribe' header 

README.md
See:
- https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md022---headings-should-be-surrounded-by-blank-lines
- https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md036---emphasis-used-instead-of-a-heading
Minor typo fix and markdown syntax in readme
...
=> Fix typo and markdown lint rules 022 and 036

docs/docs/reference/server-config.rst
There is a typo in the document: https://isso-comments.de/docs/reference/server-config/#smtp
=> docs: server-config: Fix typo in SMTP SSL

isso/js/app/i18n/ar.js
Add proper Arabic translation.
=> add ar (arabic) translation

docs/community.rst
Add a reference to the Easypanel template
This adds a reference to the Easypanel template to make deployment easier for Isso users.
This makes deployment easier, and uses all current configuration values.
=> Add reference to Easypanel

.github/workflows/python-package.yml, .github/workflows/python-tests.yml
These are required for PRs to land.
=> Always run python tests

README.md
See https://matrix.org/blog/2023/07/deportalling-libera-chat/
Fixes #989
=> Drop reference to matrix bridge

contrib/isso-dev.cfg, contrib/isso.sample.cfg, docs/community.rst, docs/docs/contributing/infrastructure.rst, docs/docs/guides/quickstart.rst, docs/docs/reference/client-config.rst, docs/docs/reference/installation.rst, docs/index.html
* docs: client-config: Correct default val for reveal-on-click
* [nit] docs: infra: Reflect auto-build of testbed img
* docs: Remove remaining mentions of Matrix-IRC bridge
This is a fixup of https://github.com/isso-comments/isso/pull/1011 which did
not entirely remove all mentions
Also make the low participation in the IRC channel clearer
* docs/installation: Expand AUR, mention removal from Debian
* docs,contrib: Suggest dbpath under /db/ more strongly
Otherwise users would have the docker daemon destroy their databases on every container restart
Just miscellaneous small changes, nothing major
=> docs: Misc changes for dropped IRC bridge, dbpath in docker, distro packaging

CHANGES.rst, isso/js/app/i18n.js, isso/js/app/i18n/ja.js
Adds Japanese translation. 
Most Japanese can only read Japanese(・ω<) .
=> Add Japanese translation
